[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Documentation Maeva Palace"
authors = [{name = "THL Technologies", email = "contact@thltechnologies.com"}]
dynamic = ["version", "description"]
